export type Property = {
  id: number;
  titulo: string;
  direccion: string;
  tipoPropiedad: string;
  tipoOperacion: "venta" | "renta" | "traspaso";
  precio: number;
  habitaciones: number;
  banos: number;
  estacionamientos: number;
  metros: number;
  antiguedad: number;
  fecha: string;
  descripcion: string;
  imagenes: string[];
  ambientes: string[];
  servicios: string[];
  amenidades: string[];
  exteriores: string[];
  extras: string[];
  detalles: {
    estadoConservacion: string;
    balcon: number;
    elevador: number;
    bodega: number;
    nivelesConstruidos: number;
    estanciaMinima: number;
    disponibilidad: string;
  };
};
